### ISSUE TITLE
v0.7.0 Release

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/libsodium-net#102]
Last call for 0.7.0 release. Please say something now if you have an issue with this release.

@fraga @bitbeans @deckar01 

**Change Log:**

* libsodium v1.0.2
* New [documentation](http://bitbeans.gitbooks.io/libsodium-net/content/) (h/t @bitbeans)
* Added support for streaming BLAKE2b hashing (h/t @deckar01)
* Updated `HashSaltPersonal` to support variable length output (h/t @bitbeans)
* Fixes and test for thread safety (h/t @deckar01)
* Better handling for unit test with unusual memory requirements (h/t @deckar01)

**Comment by fraga** [comment]
Seems fine to me :)

**Comment by bitbeans** [comment]
:+1: 

the documentation should be up-to-date.

**Comment by adamcaudill** [comment]
Released:

https://github.com/adamcaudill/libsodium-net/releases/tag/v0.7.0
https://www.nuget.org/packages/libsodium-net/
