### ISSUE TITLE
Version 0.8 Release

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/libsodium-net#106]
Updated NuGet Package: https://www.nuget.org/packages/libsodium-net/0.8.0-beta1

Only change is to update to libsodium 1.0.3. If no issues, would like to release soon.

@fraga @bitbeans

**Comment by fraga** [comment]
Should be good @adacaudill

**Comment by bitbeans** [comment]
I tested StreamCryptor with the new beta package.

:+1:

**Comment by adamcaudill** [comment]
Updated beta with `SealedPublicKeyBox`:

https://www.nuget.org/packages/libsodium-net/0.8.0-beta2

**Comment by fraga** [comment]
@adamcaudill are you still signing the releases?

**Comment by adamcaudill** [comment]
Yes; just renewed my signing cert actually. 0.8.0 will be the first release with the new cert.

**Comment by fraga** [comment]
Great!

**Comment by adamcaudill** [comment]
Released: https://github.com/adamcaudill/libsodium-net/releases/tag/v0.8.0
