### ISSUE TITLE
Simplify Readme

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/libsodium-net#108]
As we have the assume gitbook that @bitbeans put together, can we simplify the readme by removing all of the methods supported - or changing it to something simpler. It seems redundant now, and makes the readme harder to read and maintain.

Thoughts?

@fraga

**Comment by fraga** [comment]
Agree. Should we just remove all the content from Readme.MD and just refer the gitbook?

**Comment by adamcaudill** [comment]
That's what I'm thinking - having it the readme really isn't helpful, and the docs are far better.

**Comment by bitbeans** [comment]
Yeah i also agree to this.

The only thing i don`t like at gitbook.io is the missing SSL support on the book sites. :)

**Comment by fraga** [comment]
I see. Is this a hosting issue like can we host this book in GitHub?

**Comment by bitbeans** [comment]
Reply from gitbook:

>Hi Christian,
This is currently not possible, but we are working on integrating a new CDN for books content with SSL support for all hosted books.
Best Regards,
samy
Samy Pessé, Co-founder of GitBook

**Comment by fraga** [comment]
Should we wait or just create a reference to the gitbook in the readme?

**Comment by adamcaudill** [comment]
Thanks for getting a response from them @bitbeans.

We currently have the gitbook listed [here](https://github.com/adamcaudill/libsodium-net/blob/master/README.md#documentation), so I would say that we just remove [this](https://github.com/adamcaudill/libsodium-net/blob/master/README.md#methods-supported) section. 

For now, I'm comfortable with referencing the doc as is, and then opening a separate ticket to track one means or another of getting it behind TLS.

**Comment by bitbeans** [comment]
@adamcaudill  yes, i also can live with this. :)

The entry page: https://www.gitbook.com/book/bitbeans/libsodium-net/details supports SSL.
And also the downloads (PDF,..,..) are behind SSL.

So it`s only the book itself (if you want read it online).

**Comment by bitbeans** [comment]
So? Who will remove the old docs? :)

**Comment by adamcaudill** [comment]
Done. 

It occurred to me that removing this may reduce the discoverability via Google, so may need to add a few notes just to get some of the keywords back in, but we can address that later in needed.
