### ISSUE TITLE
crypto_aead_chacha20poly1305_*

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/libsodium-net#109]
We should add `crypto_aead_chacha20poly1305_*` support. 

http://doc.libsodium.org/secret-key_cryptography/aead.html

**Comment by bitbeans** [comment]
Do you mean the ietf compatible version?

```
crypto_aead_chacha20poly1305_ietf_encrypt
crypto_aead_chacha20poly1305_ietf_decrypt
```

I we already have:
```
crypto_aead_chacha20poly1305_encrypt
crypto_aead_chacha20poly1305_decrypt
```

http://bitbeans.gitbooks.io/libsodium-net/content/secret-key_cryptography/aead.html

**Comment by adamcaudill** [comment]
...

So, apparently I'm blind and Github search is failing me.
