### ISSUE TITLE
Libsodium memory management functions?

### ISSUE THREAD

**Issue by paragonie-scott** [adamcaudill/libsodium-net#112]
Is there any plan to add support for libsodium's memory wiping utilities to this wrapper? Some of them might be useful (e.g. `sodium_memzero()` for  preventing ephemeral keys from persisting in memory).

**Comment by ekodo** [comment]
Would`t this break the .NET way (Garbage Collector)?

The KeyPair object inherits from ```IDisposable```, so the user can make use of the ```Dispose()``` method: https://github.com/adamcaudill/libsodium-net/blob/master/libsodium-net/KeyPair.cs#L55

memzero some objects could end in an ```ObjectDisposedException```?

@jedisct1 @adamcaudill maybe i`am wrong, but i`am also intrested in clarify this question.

**Comment by adamcaudill** [comment]
At this point there is no plan to add support for those - as that would only help with manually managed memory, and I want to avoid that if at all possible. There may be a reasonable use-case that I'm missing, if so, I'm willing to consider it.

One thing that we do though, is under Windows, `KeyPair` uses encrypted memory to store the private key when possible, so the time it's exposed in memory is minimized.
