### ISSUE TITLE
Upgrade nuget dependencies for Baseclass.Contrib.Nuget.Output on next release

### ISSUE THREAD

**Issue by bitbeans** [adamcaudill/libsodium-net#114]
There are some changes in the msbuild path (VS2015).
An upgrade to Baseclass.Contrib.Nuget.Output 2.1.0 will fix this.

**Comment by adamcaudill** [comment]
We aren't specifying a version in the .nuspec, so *my understanding is* it will use the latest version, so we should be good here. Maybe. Unless NuGet does something different than what the documentation says. Which is always possible.

If this isn't working, I'll go ahead and specify the version - but if it does pull the latest like the docs say, then I'd like to stick with that.

**Comment by bitbeans** [comment]
I just created a new test project in VS2015.

If i install libsodium-net.0.9.0-beta4 with the nuget package manager, then Baseclass.Contrib.Nuget.Output.1.0.0 is also installed.

**Comment by adamcaudill** [comment]
Great, so the NuGet documentation is wrong.

I've pushed a new beta that is bound to 2.1.0, that should resolve this.

**Comment by bitbeans** [comment]
:+1: ok now it works out of the box again

**Comment by adamcaudill** [comment]
Excellent! Thanks for testing it.
