### ISSUE TITLE
0.9.0 Release

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/libsodium-net#116]
@fraga @bitbeans

I just released 0.9 beta4; when we are all comfortable, I'll release 0.9.0 final.

**Comment by bitbeans** [comment]
from my side everything is ok, the docs are up to date.

**Comment by bitbeans** [comment]
@fraga can you check the current beta-5, so adam can release a new stable package? :)

**Comment by fraga** [comment]
Hey guys I will just arrived from vacation will do it on monday. Tks

**Comment by bitbeans** [comment]
status? :)

**Comment by fraga** [comment]
1 week later...

I'm good too

**Comment by bitbeans** [comment]
awesome! thank you

**Comment by bitbeans** [comment]
@adamcaudill is there a release date? :)

**Comment by adamcaudill** [comment]
There will be one more beta release, after your PR is merged - then we'll release.

**Comment by bitbeans** [comment]
good news :D

**Comment by adamcaudill** [comment]
New beta; once everybody agrees that it looks good, I'll release 0.9.0:

https://www.nuget.org/packages/libsodium-net/0.9.0-beta6

**Comment by bitbeans** [comment]
:+1:

**Comment by fraga** [comment]
I'm ok with it :)

**Comment by adamcaudill** [comment]
Months late, but it's out!

https://github.com/adamcaudill/libsodium-net/releases/tag/v0.9.0
https://www.nuget.org/packages/libsodium-net/0.9.0

**Comment by bitbeans** [comment]
https://bitbeans.gitbooks.io/libsodium-net/content/index.html updated

**Comment by adamcaudill** [comment]
Thanks @bitbeans - really appreciate all the work on this release, and the work on the documentation.
