### ISSUE TITLE
SecretAead insufficient nonce length not yet updated

### ISSUE THREAD

**Issue by Timovzl** [adamcaudill/libsodium-net#122]
SecretAead has a nonce of only 8 bytes, which is considered insufficient.

Libsodium has addressed this issue and moved to 64 bytes. (https://download.libsodium.org/doc/secret-key_cryptography/aead.html)

**Comment by Timovzl** [comment]
I was mistaken. I was looking at the wrong class.

Interestingly, it looks like **some** methods have a sufficiently long nonce to allow randomized use rather than incrementing: **4.1 (secret-key authenticated encryption)** and **5.1 (public-key authenticated encryption)**.

Others, however, have a short nonce that calls for incrementing a counter: **4.3 (secret key AEAD)** and **8.1 (AES-256-GCM)**.

Does anyknow here know why this distinction is made?

**Comment by adamcaudill** [comment]
As I recall, it's based on the spec as defined in [NaCl](https://nacl.cr.yp.to/) - what we are doing here matches [libsodium](https://github.com/jedisct1/libsodium) itself; to dig in more, may want to open a ticket there.
