### ISSUE TITLE
`Sodium.SecretBox` padding

### ISSUE THREAD

**Issue by jedisct1** [adamcaudill/libsodium-net#133]
`Sodium.SecretBox` calls `crypto_secretbox()`, which prepends 16 zeros to the ciphertext.

This is inconsistent with all other bindings, but also with `Sodium.PublicKeyBox` that calls the `crypto_box_easy()` API.

Shouldn't `Sodium.SecretBox` call `crypto_secretbox_easy()` instead?

**Comment by bitbeans** [comment]
@jedisct1 you are right.
This may break backward compatibility.

@adamcaudill I added the easy bindings, but maybe this should be the default in the new release?

See: https://github.com/bitbeans/libsodium-net/commit/0d718a4c4d2d1f148a081864496fff7620245956
