### ISSUE TITLE
May I use this lib in production environment?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [adamcaudill/libsodium-net#135]
I need use libsodium in C#. but only see this one way.
so , may be the project to stable to be use in production environment?

**Comment by adamcaudill** [comment]
This library is used by multiple other libraries and I know it's used in at least a few production environments. The library is stable, and to the best of my knowledge, is safe for use in production environments.

**Comment by Lyoko-Jeremie** [comment]
but in my view, the lib not fix the problem where ZERO_BYTES befor ciphertext in `Utilities.BinaryToHex` and `SecretBox.Create` untill last commit.

i need use sodlium to protect privately-owned socket communicate between c++ server side and C# client side. SO ,may be this lib can use similar like c libsodium and communicate with that ?
