### ISSUE TITLE
Latest libsodium-net with Argon Not Available in NuGet

### ISSUE THREAD

**Issue by aaronkerwin** [adamcaudill/libsodium-net#139]
We are seriously considering using libsodium-net for production use and we want to use the Argon2i hashing algorithm. We haven't found the latest library anywhere other than github and it's only the source code. Based upon the documentation and earlier versions I would expect to find the latest in NuGet, but it's not there.

**Comment by bitbeans** [comment]
Only @adamcaudill can release a new nuget package.
The libsodium-net documentation is also out of date: https://bitbeans.gitbooks.io/libsodium-net/content/password_hashing/index.html 

i will update the docs after the new release.

**Comment by aaronkerwin** [comment]
Thanks @bitbeans. I really hope that gets released ASAP, it's been out of date for a while and possibly creates some doubt of the legitimacy of the library... I would love to see that go away since I am about to direct my team to use it. In addition, it would be best if people referenced the official package via NuGet instead of downloading the source, building it, and hosting their own version of it via an independent NuGet (which we are about to do).

**Comment by adamcaudill** [comment]
Apologies for the delay (in the process of moving, and build machine was packed away) - I was hoping to get a new beta out yesterday, but I'm still waiting on my new code signing certificate to be issued. Hopefully tomorrow evening at the latest.

If there are no issues with the beta, I'll release 0.10 at the end of the week.

**Comment by aaronkerwin** [comment]
Thanks Adam! What needs to be accomplished to move it out of beta? Is it anything others can help with?


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Adam Caudill <notifications@github.com> Date: 6/28/16  8:27 PM  (GMT-07:00) To: adamcaudill/libsodium-net <libsodium-net@noreply.github.com> Cc: Aaron Kerwin <aaron.kerwin@gmail.com>, Author <author@noreply.github.com> Subject: Re: [adamcaudill/libsodium-net] Latest libsodium-net with Argon Not
  Available in NuGet (#139) 
Apologies for the delay (in the process of moving, and build machine was packed away) - I was hoping to get a new beta out yesterday, but I'm still waiting on my new code signing certificate to be issued. Hopefully tomorrow evening at the latest.

If there are no issues with the beta, I'll release 0.10 at the end of the week.

**Comment by bitbeans** [comment]
@adamcaudill @fraga travis seems to be broken.
But i think this: https://github.com/adamcaudill/libsodium-net/pull/140 should be merged before the new beta package.

**Comment by adamcaudill** [comment]
@aaronkerwin @bitbeans Status update: It's taking longer than normal to renew the code signing certificate that I use for these builds, but I believe that they now have all of the documentation needed. As soon as I get the renewed certificate, I'll push to NuGet.

**Comment by adamcaudill** [comment]
Signing certificate finally sorted - 0.10.0-beta3 is now available: https://www.nuget.org/packages/libsodium-net/0.10.0-beta3
