### ISSUE TITLE
v0.10.0 Release

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/libsodium-net#143]
I'd like to release v0.10 soon - please let me know if you have any objections.

@fraga @bitbeans

**Comment by bitbeans** [comment]
:+1:

**Comment by fraga** [comment]
I am good too :)

**Comment by memsis** [comment]
Which libsodium would be included in the next release ?

**Comment by memsis** [comment]
@adamcaudill Have you planned a date for the next release ?
