### ISSUE TITLE
Is Argon2id supported?

### ISSUE THREAD

**Issue by rc201612** [adamcaudill/libsodium-net#168]
Hi 

I read in the documentation from libsodium that as of 1.0.15 Argon2id is the default hashing algorithm.

Is this supported by this library?

**Comment by monoman** [comment]
From https://github.com/adamcaudill/libsodium-net/blob/4ae7898db8cd2d97b958ef53f1fe44c9e0e71ba6/libsodium-net/PasswordHash.cs it seems it always  uses the default algorithm. so if you use version 1.0.15 and up of libsodium.net it is the default also: https://github.com/jedisct1/libsodium/releases/tag/1.0.15
